// // -- MySQL Script generated by MySQL Workbench
// // -- Mon Dec  2 12:41:23 2019
// // -- Model: New Model    Version: 1.0
// // -- MySQL Workbench Forward Engineering

// SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
// SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
// SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

// // -- -----------------------------------------------------
// // -- Schema mydb
// // -- -----------------------------------------------------

// // -- -----------------------------------------------------
// // -- Schema mydb
// // -- -----------------------------------------------------
// CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
// USE `mydb` ;

// -- -----------------------------------------------------
// -- Table `mydb`.`Cocktail`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `mydb`.`Cocktail` (
// `id_cocktail` INT NOT NULL AUTO_INCREMENT,
// `api_id` VARCHAR(45) NULL,
// `cocktail_name` VARCHAR(45) NOT NULL,
// `instructions` VARCHAR(500) NOT NULL,
// `source` VARCHAR(45) NULL,
// PRIMARY KEY (`id_cocktail`),
// UNIQUE INDEX `id_cocktail_UNIQUE` (`id_cocktail` ASC) VISIBLE)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `mydb`.`Receptacle`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `mydb`.`Receptacle` (
// `id_Receptacle` INT NOT NULL AUTO_INCREMENT,
// `receptacle_name` VARCHAR(45) NOT NULL,
// `cocktail_id` INT NULL,
// PRIMARY KEY (`id_Receptacle`),
// UNIQUE INDEX `id_Receptacle_UNIQUE` (`id_Receptacle` ASC) VISIBLE,
// INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
// CONSTRAINT `id_cocktail`
//     FOREIGN KEY (`cocktail_id`)
//     REFERENCES `mydb`.`Cocktail` (`id_cocktail`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `mydb`.`Categories`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
// `id_categories` INT NOT NULL AUTO_INCREMENT,
// `caterogy_name` VARCHAR(45) NOT NULL,
// `cocktail_id` INT NOT NULL,
// PRIMARY KEY (`id_categories`),
// UNIQUE INDEX `id_categories_UNIQUE` (`id_categories` ASC) VISIBLE,
// INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
// CONSTRAINT `cocktail_id`
//     FOREIGN KEY (`cocktail_id`)
//     REFERENCES `mydb`.`Cocktail` (`id_cocktail`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `mydb`.`ingredients`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
// `id_ingredients` INT NOT NULL AUTO_INCREMENT,
// `ingredient_name` VARCHAR(45) NOT NULL,
// `units` VARCHAR(45) NULL,
// PRIMARY KEY (`id_ingredients`),
// UNIQUE INDEX `id_ingredients_UNIQUE` (`id_ingredients` ASC) VISIBLE)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `mydb`.`c_to_i_relational`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `mydb`.`c_to_i_relational` (
// `relational_id` INT NOT NULL AUTO_INCREMENT,
// `cocktail_id` INT NOT NULL,
// `ingredient_id` INT NOT NULL,
// INDEX `cocktail_id_idx` (`cocktail_id` ASC) VISIBLE,
// INDEX `ingredient_id_idx` (`ingredient_id` ASC) VISIBLE,
// PRIMARY KEY (`relational_id`),
// UNIQUE INDEX `relational_id_UNIQUE` (`relational_id` ASC) VISIBLE,
// CONSTRAINT `cocktail_id`
//     FOREIGN KEY (`cocktail_id`)
//     REFERENCES `mydb`.`Cocktail` (`id_cocktail`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION,
// CONSTRAINT `ingredient_id`
//     FOREIGN KEY (`ingredient_id`)
//     REFERENCES `mydb`.`ingredients` (`id_ingredients`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// SET SQL_MODE=@OLD_SQL_MODE;
// SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
// SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
